### ISSUE TITLE
Dissecting golang's HandlerFunc, Handle and DefaultServeMux

### ISSUE THREAD

**Issue by bdaglish** [amitsaha/amitsaha.github.io#2]
Unless I'm going blind, I can't see the MyResponseWriter Write() method in the final example - just Header() and WriteHeader(). Great article though!

**Comment by amitsaha** [comment]
Thanks, i have been meaning to fix it for a while.

**Comment by amitsaha** [comment]
Fixed in https://github.com/amitsaha/echorand.me/commit/cdcab89ab16f1d3abafa7611de6a8b0c006834c9
